In [1]:
%matplotlib inline
import numpy as np

In [2]:
from dsets import getCandidateInfoList, getCt, LunaDataset
candidateInfo_list = getCandidateInfoList(requireOnDisk_bool=False)
positiveInfo_list = [x for x in candidateInfo_list if x[0]]
diameter_list = [x[1] for x in positiveInfo_list]

In [3]:
print(len(positiveInfo_list))
print(positiveInfo_list[0])

1351
CandidateInfoTuple(isNodule_bool=True, diameter_mm=32.27003025, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.287966244644280690737019247886', center_xyz=(67.61451718, 85.02525992, -109.8084416))


In [4]:
for i in range(0, len(diameter_list), 100):
    print('{:4}  {:4.1f} mm'.format(i, diameter_list[i]))

   0  32.3 mm
 100  17.7 mm
 200  13.0 mm
 300  10.0 mm
 400   8.2 mm
 500   7.0 mm
 600   6.3 mm
 700   5.7 mm
 800   5.1 mm
 900   4.7 mm
1000   4.0 mm
1100   0.0 mm
1200   0.0 mm
1300   0.0 mm


In [6]:
for candidateInfo_tup in positiveInfo_list[:10]:
    print(candidateInfo_tup)
for candidateInfo_tup in positiveInfo_list[-10:]:
    print(candidateInfo_tup)
    
for candidateInfo_tup in positiveInfo_list:
    if candidateInfo_tup.series_uid.endswith('565'):
        print(candidateInfo_tup)

CandidateInfoTuple(isNodule_bool=True, diameter_mm=32.27003025, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.287966244644280690737019247886', center_xyz=(67.61451718, 85.02525992, -109.8084416))
CandidateInfoTuple(isNodule_bool=True, diameter_mm=30.61040636, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.112740418331256326754121315800', center_xyz=(47.90350511, 37.60442008, -99.93417567))
CandidateInfoTuple(isNodule_bool=True, diameter_mm=30.61040636, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.112740418331256326754121315800', center_xyz=(44.19, 37.79, -107.01))
CandidateInfoTuple(isNodule_bool=True, diameter_mm=30.61040636, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.112740418331256326754121315800', center_xyz=(40.69, 32.19, -97.15))
CandidateInfoTuple(isNodule_bool=True, diameter_mm=27.44242293, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.943403138251347598519939390311', center_xyz=(-45.29440163, 74.86925386, -97.52812481))
CandidateInfoTuple(isNodule_bool=True, diameter_mm=27.

In [7]:
np.histogram(diameter_list)

(array([323, 466, 248, 111,  71,  57,  37,  29,   5,   4], dtype=int64),
 array([ 0.        ,  3.22700302,  6.45400605,  9.68100907, 12.9080121 ,
        16.13501512, 19.36201815, 22.58902117, 25.8160242 , 29.04302722,
        32.27003025]))

In [8]:
from vis import findPositiveSamples, showCandidate
positiveSample_list = findPositiveSamples()

2022-09-22 15:21:52,819 INFO     pid:3032 LunaDataset.dsets:221:__init__ <LunaDataset.dsets.LunaDataset object at 0x000001DCA8938310>: 551065 training samples


0 CandidateInfoTuple(isNodule_bool=True, diameter_mm=5.997708724, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.122914038048856168343065566972', center_xyz=(73.8113187345, 91.489265475, -226.594524675))
1 CandidateInfoTuple(isNodule_bool=True, diameter_mm=5.104384596, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.323859712968543712594665815359', center_xyz=(-80.59, -74.34, -114.66))
2 CandidateInfoTuple(isNodule_bool=True, diameter_mm=6.436398619, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.219428004988664846407984058588', center_xyz=(127.41, 44.72, -188.9))
3 CandidateInfoTuple(isNodule_bool=True, diameter_mm=4.290410287, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.161067514225109999586362698069', center_xyz=(-89.73, 63.62, -161.78))
4 CandidateInfoTuple(isNodule_bool=True, diameter_mm=7.595614881, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.280072876841890439628529365478', center_xyz=(-85.73, -167.72, -126.97))
5 CandidateInfoTuple(isNodule_bool=True, diameter_mm=4.522057979, s

In [20]:
positiveSample_list[11]

CandidateInfoTuple(isNodule_bool=True, diameter_mm=8.623614727, series_uid='1.3.6.1.4.1.14519.5.2.1.6279.6001.301582691063019848479942618641', center_xyz=(85.30735954, -37.60796494, -100.46361505))

In [26]:
series_uid = positiveSample_list[11][2]
showCandidate(series_uid = series_uid)

2022-09-22 15:40:37,434 INFO     pid:3032 LunaDataset.dsets:221:__init__ <LunaDataset.dsets.LunaDataset object at 0x000001DCB37B0FD0>: 415 training samples


<IPython.core.display.Javascript object>

1.3.6.1.4.1.14519.5.2.1.6279.6001.301582691063019848479942618641 259 False [259]


In [35]:
test = LunaDataset(series_uid = series_uid)
print(test[414])

2022-09-22 15:41:59,195 INFO     pid:3032 dsets:221:__init__ <dsets.LunaDataset object at 0x000001DCB3796F10>: 415 training samples


(tensor([[[[ -986.,  -992.,  -996.,  ...,  -960.,  -948.,  -948.],
          [-1000., -1000.,  -986.,  ...,  -970.,  -962.,  -952.],
          [-1000.,  -988.,  -960.,  ...,  -982.,  -982.,  -964.],
          ...,
          [ -946.,  -936.,  -964.,  ...,  -956.,  -960.,  -974.],
          [ -944.,  -940.,  -958.,  ...,  -950.,  -976.,  -980.],
          [ -952.,  -966.,  -966.,  ...,  -956.,  -974.,  -980.]],

         [[ -982.,  -986.,  -996.,  ...,  -952.,  -942.,  -928.],
          [ -990.,  -992.,  -994.,  ...,  -956.,  -952.,  -938.],
          [-1000.,  -986.,  -966.,  ...,  -960.,  -958.,  -948.],
          ...,
          [ -968.,  -958.,  -972.,  ...,  -956.,  -958.,  -974.],
          [ -980.,  -974.,  -994.,  ...,  -952.,  -964.,  -970.],
          [ -990.,  -984.,  -976.,  ...,  -958.,  -968.,  -968.]],

         [[ -974.,  -970.,  -978.,  ...,  -940.,  -920.,  -904.],
          [ -984.,  -974.,  -968.,  ...,  -950.,  -948.,  -952.],
          [ -986.,  -972.,  -956.,  ..., 

In [11]:
series_uid = '1.3.6.1.4.1.14519.5.2.1.6279.6001.124154461048929153767743874565'
showCandidate(series_uid)

2022-09-22 15:12:19,888 INFO     pid:3124 LunaDataset.dsets:221:__init__ <LunaDataset.dsets.LunaDataset object at 0x000002E2B79B0220>: 1061 training samples


<IPython.core.display.Javascript object>

1.3.6.1.4.1.14519.5.2.1.6279.6001.124154461048929153767743874565 794 False [794]


In [12]:
series_uid = '1.3.6.1.4.1.14519.5.2.1.6279.6001.126264578931778258890371755354'
showCandidate(series_uid)

2022-09-22 15:12:23,910 INFO     pid:3124 LunaDataset.dsets:221:__init__ <LunaDataset.dsets.LunaDataset object at 0x000002E2B3B790A0>: 605 training samples


<IPython.core.display.Javascript object>

1.3.6.1.4.1.14519.5.2.1.6279.6001.126264578931778258890371755354 488 False [488]


In [13]:
LunaDataset()[0]

2022-09-22 15:12:31,357 INFO     pid:3124 dsets:221:__init__ <dsets.LunaDataset object at 0x000002E2BA00B250>: 551065 training samples


(tensor([[[[ -77.,  -37.,  -63.,  ...,  -20.,  -63.,  -68.],
           [-103.,  -82.,  -81.,  ...,  -41.,  -76.,  -65.],
           [-117.,  -99.,  -77.,  ..., -134., -128., -120.],
           ...,
           [   9.,    5.,    3.,  ..., -903., -887., -900.],
           [  -2.,   22.,   27.,  ..., -917., -888., -878.],
           [  10.,   40.,   32.,  ..., -860., -820., -847.]],
 
          [[ -97.,  -89.,  -40.,  ...,  -56.,  -83., -103.],
           [-135., -114.,  -65.,  ...,  -42.,  -88.,  -76.],
           [-126.,  -71.,  -44.,  ...,  -57.,  -56.,  -35.],
           ...,
           [  -4.,   22.,   -2.,  ..., -924., -909., -914.],
           [  -5.,    9.,    6.,  ..., -933., -905., -879.],
           [   0.,    4.,   10.,  ..., -888., -837., -845.]],
 
          [[ -77., -102.,  -14.,  ...,  -56.,  -67., -106.],
           [-112., -109.,  -18.,  ...,  -21.,  -58.,  -82.],
           [-123.,  -75.,  -27.,  ...,  -35.,  -50.,  -46.],
           ...,
           [  17.,   41.,   16.

In [14]:
import numpy as np
import ipyvolume as ipv
V = np.zeros((128,128,128)) # our 3d array
# outer box
V[30:-30,30:-30,30:-30] = 0.75
V[35:-35,35:-35,35:-35] = 0.0
# inner box
V[50:-50,50:-50,50:-50] = 0.25
V[55:-55,55:-55,55:-55] = 0.0
ipv.quickvolshow(V, level=[0.25, 0.75], opacity=0.03, level_width=0.1, data_min=0, data_max=1)


c:\Users\f\anaconda3\envs\Lung_cancer\lib\site-packages\ipyvolume\serialize.py:81: RuntimeWarning: invalid value encountered in divide
  gradient = gradient / np.sqrt(gradient[0]**2 + gradient[1]**2 + gradient[2]**2)


In [13]:
ct = getCt(series_uid)
ipv.quickvolshow(ct.hu_a, level=[0.25, 0.5, 0.9], opacity=0.1, level_width=0.1, data_min=-1000, data_max=1000)

c:\Users\f\anaconda3\envs\Lung_cancer\lib\site-packages\ipyvolume\pylab.py:681: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if memorder is 'F':
c:\Users\f\anaconda3\envs\Lung_cancer\lib\site-packages\ipyvolume\pylab.py:681: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if memorder is 'F':


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

# Note: the following visualization doesn't look very good.
It's only included here for completeness. 

In [ ]:
import scipy.ndimage.morphology
def build2dLungMask(ct, mask_ndx, threshold_gcc = 0.7):
    dense_mask = ct.hu_a[mask_ndx] > threshold_gcc
    denoise_mask = scipy.ndimage.morphology.binary_closing(dense_mask, iterations=2)
    tissue_mask = scipy.ndimage.morphology.binary_opening(denoise_mask, iterations=10)
    body_mask = scipy.ndimage.morphology.binary_fill_holes(tissue_mask)
    air_mask = scipy.ndimage.morphology.binary_fill_holes(body_mask & ~tissue_mask)

    lung_mask = scipy.ndimage.morphology.binary_dilation(air_mask, iterations=2)

    return air_mask, lung_mask, dense_mask, denoise_mask, tissue_mask, body_mask


def build3dLungMask(ct):
    air_mask, lung_mask, dense_mask, denoise_mask, tissue_mask, body_mask = mask_list = \
        [np.zeros_like(ct.hu_a, dtype=np.bool) for _ in range(6)]

    for mask_ndx in range(ct.hu_a.shape[0]):
        for i, mask_ary in enumerate(build2dLungMask(ct, mask_ndx)):
            mask_list[i][mask_ndx] = mask_ary

    return air_mask, lung_mask, dense_mask, denoise_mask, tissue_mask, body_mask

In [ ]:
from dsets import getCt
ct = getCt(series_uid)
air_mask, lung_mask, dense_mask, denoise_mask, tissue_mask, body_mask = build3dLungMask(ct)


In [ ]:
bones = ct.hu_a * (ct.hu_a > 1.5)
lungs = ct.hu_a * air_mask
ipv.figure()
ipv.pylab.volshow(bones + lungs, level=[0.17, 0.17, 0.23], data_min=100, data_max=900)
ipv.show()

C:\Users\elis\Miniconda3\envs\book\lib\site-packages\ipyvolume\widgets.py:179: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data_view = self.data_original[view]
C:\Users\elis\Miniconda3\envs\book\lib\site-packages\ipyvolume\utils.py:204: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data = (data[slices1] + data[slices2])/2
C:\Users\elis\Miniconda3\envs\book\lib\site-packages\ipyvolume\serialize.py:81: RuntimeWarning: invalid value encountered in true_divide
  gradient = gradient / np.sqrt(gradient[0]**2 + gradient[1]**2 + gradient[2]**2)